language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t awais1331/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true awais1331/react-test npm test

after_success:
  - docker build -t awais1331/multi-client ./client
  - docker build -t awais1331/multi-nginx ./nginx
  - docker build -t awais1331/multi-server ./server
  - docker build -t awais1331/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to Docker Hub
  - docker push awais1331/multi-client
  - docker push awais1331/multi-nginx
  - docker push awais1331/multi-server
  - docker push awais1331/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-628236557397
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
